CREATE TABLE `test`.`Untitled`  (
  `mid` bigint(20) NOT NULL AUTO_INCREMENT,
  `uk` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `us` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `_id` varchar(1255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `cipin` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ciyi` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `cizu` json NULL,
  `danci` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `fushu` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `gaokao` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `gkcipin` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `jinyicibx` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kaoyan` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kydgcipinxh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kydgzimuxh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc2000` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc2000sc` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc2000xh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc3000` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc3000xh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc600` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc600sc` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `kygpc600xh` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `liju` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `lijufanyi` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `liuji` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ljcipin` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `lwdanci` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `readdc` json NULL,
  `shucibj` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `siji` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `sjcipin` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `tgc` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `tgci` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `tonggen` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `tonggenci` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `tongyici` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `undefined` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `wdreaddc` json NULL,
  `xuhao` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `xzjxs` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `xzwcs` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `ybgqs` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  `zhangwo` json NULL,
  `zhentiliju` json NULL,
  `zhuji` text CHARACTER SET utf8 COLLATE utf8_general_ci NULL,
  PRIMARY KEY (`mid`) USING BTREE
) ENGINE = MyISAM AUTO_INCREMENT = 89904 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic;