spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8